# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_gain_exposure.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 73)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.sldr_gain = QtWidgets.QSlider(Form)
        self.sldr_gain.setMaximum(31)
        self.sldr_gain.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_gain.setObjectName("sldr_gain")
        self.gridLayout.addWidget(self.sldr_gain, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.sldr_exposure = QtWidgets.QSlider(Form)
        self.sldr_exposure.setMaximum(450)
        self.sldr_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.sldr_exposure.setObjectName("sldr_exposure")
        self.gridLayout.addWidget(self.sldr_exposure, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lbl_wexposure = QtWidgets.QLabel(Form)
        self.lbl_wexposure.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_wexposure.setText("")
        self.lbl_wexposure.setObjectName("lbl_wexposure")
        self.gridLayout.addWidget(self.lbl_wexposure, 0, 2, 1, 1)
        self.lbl_wgain = QtWidgets.QLabel(Form)
        self.lbl_wgain.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_wgain.setText("")
        self.lbl_wgain.setObjectName("lbl_wgain")
        self.gridLayout.addWidget(self.lbl_wgain, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.sldr_exposure, self.sldr_gain)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Exposure:"))
        self.label_2.setText(_translate("Form", "Gain:"))
