# Config file - major
FOLDER_STARTUP = "FOLDER_STARTUP"
FOLDER_LOG = "FOLDER_LOG"
FOLDER_PLUGINS = "FOLDER_PLUGINS"
FOLDER_PROFILES = "FOLDER_PROFILES"
FOLDER_IMAGES = "FOLDER_IMAGES"
FOLDER_HTML = "FOLDER_HTML"

LOGO_FILE = "LOGO_FILE"

MOVEPLUGINS = "MOVEPLUGINS"

# DATA Image
DATA_IMAGE = "DATA_IMAGE"

# camera id
CAMERA_ID = "CAMERA_ID"

# Qsettings storage
SETTINGS = "SETTINGS"

# logging
LOGGING_MAIN_FILE = "LOGGING_MAIN_FILE"
LOGGING_MAIN_FORMAT = "LOGGING_MAIN_FORMAT"
LOGGING_MAIN_DATE = "LOGGING_MAIN_DATE"
LOGGING_FILE_FORMAT = "LOGGING_FILE_FORMAT"
LOGGING_FILE_DATE = "LOGGING_FILE_DATE"

# window
WINDOW_TITLE = "WINDOW_TITLE"
DIALOG_SELECTOR_TITLE = "DIALOG_SELECTOR_TITLE"

# PROFILES
PROFILE_SOURCE = "PROFILE_SOURCE"
PROFILE_PACKAGE = "PROFILE_PACKAGE"
PROFILE_IMPORTS = "imports"
PROFILE_SETUP = "setup"
PROFILE_FOLDER = "PROFILE_FOLDER"

# configuration Marker & Frame
MARKER_POSITION = "MARKER_POSITION"
MARKER_SIZE = "MARKER_SIZE"
MARKER_SHAPE = "MARKER_SHAPE"
MARKER_LINEWIDTH = "MARKER_LINEWIDTH"
MARKER_COLORINDEX = "MARKER_COLORINDEX"
FRAME_COLORINDEX = "FRAME_COLORINDEX"
MARKER_DISPLAY = "MARKER_DISPLAY"
FRAME_DISPLAY = "FRAME_DISPLAY"
CAMERA_NICKNAME = "CAMERA_NICKNAME"
CAMERA_DIRNAME = "CAMERA_DIRNAME"